baseURL: 'https://yudiwiratama.github.io-blog/'
languageCode: 'pt-pt'
theme: "hello-friend-4s3ti"
title: 'blog.coolapso.sh'
copyright: "All Rights Reserved"
IsMultiLingual: true
defaultContentLanguage: en

languages:
#  ja:
#    weight: 1
#    languageName: "Japanese"
  en:
    weight: 2
    params: 
      backgroundImage: "../static/coolapso.webp"
    menu: 
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts" 
          weight: 1

        - identifier: "about"
          name: "About"
          url: "https://yudiwiratama.github.io"
          weight: 2

        - identifier: "projects"
          name: "Projects"
          url: "/projects"
#        - identifier: "Project 1"
#          name: "Project 1"
#          url: "#"
#          parent: "projects"
        - identifier: "tools"
          name: "Tools"
#        - identifier: "tool1"
#          name: "tool1"
#          url: "#"
#          parent: "tools"
    #     weight: 10
#        - identifier: "Tool2"
#          name: "tool2"
#          url: '#'
#          parent: "tools"



params:
  version: "dev"
  author: 
    name: "coolapso"
  defaultTheme: "dark"
  EnableThemeToggle: true 
# gitUrl: "https://github.com/4s3ti"
  EnableSharingButtons: true
  EnableGlobalLanguageMenu: true
  backgroundImage: "static/coolapso.webp"
  backgroundEffects: true
  showPosts: true
  tags: true
# hideReadMore: true
  ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
  fontAwesome: 
    all: true
    # brands: true
    # solid: true
    # regular: true
    # kitURL: "https://kit.fontawesome.com/yourkitid.js"
  ShowReadingTime: true
  LastModDisplay: true
  tags: true
  logo:
    logoText: "yudiwiratama.sh"
    logoCursorColor: "#ffffff"
  social:
    - name: "github"
      url: "https://github.com/yudiwiratama"
    - name: "website"
      url: "https://yudiwiratama.github.io-blog"
      icon: fa-solid fa-terminal
    - name: "youtube"
      url: "https://youtube.com"
    - name: "x-twitter"
      url: "https://x.com/"
    - name: "instagram"
      url: "https://www.instagram.com"
    - name: "twitch"
      url: "https://twitch.tv/"
    - name: "Buy me a coffee"
      url: "https://www.buymeacoffee.com/"
      icon: fa-solid fa-coffee
  footer:
    showVersion: true
    socialIcons: true
    author: true
    rss: true
    trademark: true
    copyright: true
#   topText:  ["Footer Top text"]
    bottomText: [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>",
    ]
    


taxonomies:
  tag: "tags"
  category: "blog"

menu:
  main:
    - identifier: "about"
      name: "Tentang"
      url: "#"
      weight: 2

    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 1

    - identifier: "tools"
      name: "Ferramentas"

    - identifier: "projects"
      name: "Projetos"
      url: "/projects"

    - identifier: "Projeto 1"
      name: "Projeto 1"
      url: "#"
      parent: "projects"
    - identifier: "ferramenta 1"
      name: "Ferramenta 1"
      url: "#"
      parent: "tools"
    - identifier: "Ferramenta 2"
      name: "Ferramenta 2"
      parent: "tools"
      url: "#"
    - identifier: "Ferramenta 3"
      name: "Ferramenta 3"
      parent: "tools"
      url: "#"
